### ISSUE TITLE
Chargement d'une font Google bloqué en HTTPS

### ISSUE THREAD

**Issue by sebclick** [Freenews/Bug-Tracker#1]
Freenews est en HTTPS mais une font google est bloquée par Chrome car elle est chargée en HTTP.

![capture du 2016-05-09 12-07-21](https://cloud.githubusercontent.com/assets/2091615/15109999/a0186e16-15de-11e6-8727-9cd323582188.png)

Rien de grave, mais le rendu graphique pourrait être différent pour certains utilisateurs.

NB : très bonne idée ce bugtracker :+1:

**Comment by CyrilCharlier** [comment]
une résolution de ce genre de souci  => mettre url = "//url.a.charger.com/" dans les url à charger au lieu de mettre url="http://...." ou url="https://...."

ainsi cela s'adapte au protocole du client.

**Comment by ThibaultVlacich** [comment]
Hello @sebclick.

Merci pour le retour. Après investigation, il semblerait que ce soit le script pub qui charge cette font.

Je vais voir avec la régie.

**Comment by ThibaultVlacich** [comment]
Nous avons changé de régie, le problème est donc "corrigé" :)
