### ISSUE TITLE
Certificat HTTPS app.freenews.fr périmé

### ISSUE THREAD

**Issue by ombremad** [Freenews/Bug-Tracker#3]
<img width="477" alt="capture d ecran 2016-06-23 a 14 24 19" src="https://cloud.githubusercontent.com/assets/19262498/16302967/49cb9d1a-394e-11e6-948d-d0b7a3dcf2fc.png">

**Comment by isa1201** [comment]
Si on me dit quoi faire je m'en occupe !

**Comment by ThibaultVlacich** [comment]
@isa1201 Je suis entrain d'envoyer un mail à Souhail.

**Comment by SouhailJebali** [comment]
Merci pour le retour!
Ça a été corrigé.
