### ISSUE TITLE
Mode liste : pagination HS

### ISSUE THREAD

**Issue by ombremad** [Freenews/Bug-Tracker#4]
Sur la homepage, en mode liste, la pagination ne fonctionne pas.
Quelle que soit la page que l'on tente d'afficher, cela affiche toujours la 1ère page. Du coup, impossible d'accéder aux articles plus anciens par ce moyen.

<img width="756" alt="capture d ecran 2016-07-19 a 14 06 40" src="https://cloud.githubusercontent.com/assets/19262498/16949275/2ae6b62a-4dba-11e6-93bb-2acf05ab26bc.png">

**Comment by ThibaultVlacich** [comment]
Je regarderai ça ce week-end. Merci pour le retour.

**Comment by MJJone** [comment]
Je confirme c'est assez embêtant. Le problème sera t-il résolu prochainement ?

**Comment by ThibaultVlacich** [comment]
Corrigé
