### ISSUE TITLE
Bug WordPress/SMF

### ISSUE THREAD

**Issue by jmcruvellier** [Freenews/Bug-Tracker#6]
@ThibaultVlacich , @filoboss ,
 
Je viens de me rendre compte qu’il y a un bug dans l’interface entre les commentaires qui sont affichés dans WordPress et ceux du Forum SMF.
Certains commentaires apparaissent vides dans les articles WordPress alors qu’ils ne le sont pas dans le Forum.
Il semblerait que le bug concerne les commentaires incluant des citations d’autres commentaires.
Pouvez-vous y jeter un coup d’œil ?
Merci ;-)

Jean-Marc

**Comment by ThibaultVlacich** [comment]
Corrigé dans Freenews/freenews.fr#23
