### ISSUE TITLE
Application Windows Phone : Texte des articles invisible

### ISSUE THREAD

**Issue by MJJone** [Freenews/Bug-Tracker#7]
Bonjour,

le texte est invisible dans le contenu des articles : voir capture jointe
![wp_ss_20170124_0004](https://cloud.githubusercontent.com/assets/25325042/22251745/30c535fe-e24c-11e6-8bf8-16793511cb7e.png)

Merci.
Config : LUMIA 930 sous Windows 10 (Build insider)

**Comment by jmcruvellier** [comment]
Super, merci pour ce retour de bug! Je vais essayer de le reproduire et inclure la correction dans la prochaine version (qui devrait sortir d'ici peu).

**Comment by jmcruvellier** [comment]
Bon petite investigation faite, il ne s'agit pas d'un bug car je suis arrivé à ouvrir correctement l'article.
En fait, ce qu'il se passe dans ton cas c'est qu'il y a eu une perte de connexion au moment du chargement de l'article. Dans ce cas, l'appli n'affiche rien. J'ai prévu de faire apparaître un message dans la prochaine version.

![wp_ss_20170129_0001](https://cloud.githubusercontent.com/assets/14132271/22403174/77583af4-e60f-11e6-849e-7b99a1aa07b4.png)

**Comment by MJJone** [comment]
Bonjour et merci pour votre suivi.
Je rencontre tout de même le problème sur 90% des articles que j'ouvre. 
J'ai tenté de fermer l'appli et la relancer, en wifi, en 4G ça ne change rien...

Voici de nouvelles captures avec une seule qui permet de voir le contenu de l'article.

![wp_ss_20170130_0002](https://cloud.githubusercontent.com/assets/25325042/22421818/6b4680c4-e6e9-11e6-97f4-6f181a27f674.png)
![wp_ss_20170130_0001](https://cloud.githubusercontent.com/assets/25325042/22421819/6b47b232-e6e9-11e6-97cc-b5b19faad1d5.png)
![wp_ss_20170130_0004](https://cloud.githubusercontent.com/assets/25325042/22421821/6b4af000-e6e9-11e6-9c35-1a5abaf45883.png)
![wp_ss_20170130_0003](https://cloud.githubusercontent.com/assets/25325042/22421820/6b4a45ce-e6e9-11e6-83bb-20797ff0d7b6.png)

Bon courage et vivement la suite des évolutions :)

**Comment by jmcruvellier** [comment]
Ah là c'est plutôt embêtant... pouvez-vous me communiquer la version exacte de l'OS? Il me semble que vous aviez dit être sur une Insider Build.
Pour info, la version actuelle de l'application ne supporte que des build officielles 10240 à l'Anniversary Edition 14393.

**Comment by MJJone** [comment]
alors je suis sous la build insider 15014 qui est la dernière en date car je suis sur le canal de distribution "rapide" pour la distribution des builds.

Ma femme a un LUMIA 950 avec la dernière **build public** et je vous dirai ce qu'il en est après avoir installé et testé l'appli.

Enfin pour être insider depuis pas mal d'années maintenant je n'ai jamais eu d'applications, de ce type en tous cas, qui boguent... j'ai par exemple dans le même style, les applications suivantes : monwindows.com, WPCENTRAL, JEUXVIDEO.com, Allociné, ...

Bon courage.

**Comment by jmcruvellier** [comment]
Ok, j'attens votre retour d'experience sur le 950 ;-)
Concernant les Insider Build, je reste tres mefiant car d'une version a une autre les comportements des composants varient tres souvents... cependant je vais tout de meme investiguer car cela me semble etrange.

**Comment by jmcruvellier** [comment]
Sinon petite question: avez-vous essaye de raffraichir la page de l'article? Il fait cliquer sur les 3 petits points en bas a droite pour faire apparaitre le menu et ensuite cliquer sur l'icone "Rafraichir".

**Comment by MJJone** [comment]
j'ai pas encore eu le temps de tester l'appli mais ça va venir :) Sinon oui j'ai bien tenté de rafraichir les articles avec la commande prévue à cet effet mais ça ne change rien :(

A bientôt.

**Comment by MJJone** [comment]
Et voilà j'ai pu tester sur un LUMIA 950 non insider et ça fonctionne parfaitement bien :) 
De mon côté en insider sur mon L930 j'ai désinstallé  et réinstallé l'appli mais toujours le même problème.

Je ne sais pas si vous allez continuer à investiguer pour ce problème mais il faut savoir que les build insider permettent aux développeurs d'anticiper (éventuellement) des modifications de leurs applis pour les futurs mises à jours de l'OS.

La build insider en cours l'utilisation sur mon L930 sera normalement proposée au public en mars/avril 2017. Évidemment il y aura d'autre release insider avant et je vous tiendrai informé si je constate des améliorations ou des bugs.

Bon courage et vivement la suite pour découvrir les futurs mises à jour de l'appli.

**Comment by MJJone** [comment]
Bonne nouvelle !

Suite à la dernière mise à jour INSIDER (build 15025) le contenu des actus s'affiche correctement sur mon L930.

A suivre et merci pour votre suivi.

**Comment by jmcruvellier** [comment]
Merci pour votre retour!
