### ISSUE TITLE
Recherche sur le forum ne fonctionne pas.

### ISSUE THREAD

**Issue by MJJone** [Freenews/Bug-Tracker#8]
Bonjour, en effectuant une recherche sur le forum voici l'erreur retournée : 

Erreur HTTP 500
Étrange... Le site web ne parvient pas à afficher cette page
Il se peut que le site soit en cours de maintenance ou qu’une erreur de programmation se soit produite.

**Comment by ThibaultVlacich** [comment]
C'est corrigé, désolé pour la lenteur.
