### ISSUE TITLE
Android tv 10 : CEC extinction tv ne marche plus

### ISSUE THREAD

**Issue by Octopus977** [Freenews/Bug-Tracker#9]
Bonjour

Depuis le passage à android tv 10 sur ma pop, l’extinction de ma tv lors de l’arrêt de la pop ne fonctionne plus. L’allumage de la tv fonctionne lui, à l’allumage de la pop.
Les 2 fonctionnaient en version 9 d’android tv.
J’ai une tv Samsung. 

Merci

**Comment by ThibaultVlacich** [comment]
Bonjour, ce bug-tracker concerne le site freenews.fr, pas l'opérateur Free et ses produits
